<?php 
use Libraries\Sessao;
session_start();
include_once 'inc/cabecalho.phtml'; 
//dump($_SESSION);
?>
<body class="" onload="atualizarDataHora();">
    <div class="d-flex" id="wrapper">
        <?php include_once 'inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
        <!-- Top navigation-->
        <?php include_once 'inc/menu_topo.phtml'; ?>
        <div class="container-fluid bg-light p-0">
            <header class="py-3">
                <section class="container px-5">
                    <div class="row gx-5 align-items-center justify-content-center">
                        <div class="col-lg-10 col-xl-10 col-xxl-10">
                            <div class="my-3 text-center text-xl-start">
                                <a class="text-decoration-none" href="<?= DIRPAGE; ?>admin/painel"><h3 class="display-5 text-center fw-bolder text-uppercase text-dark mb-2"><i class="bi bi-rss"></i> Painel <span class="text-success">Administrativo</span></h3></a>
                            </div>
                        </div>
                    </div>
                </section>
            </header>
            <section class="container py-2">
            <h4>BEM VINDO(A) <?= $usuario['USU_NOME'] ?></h4>
            <?= Sessao::alert('OK'); ?>
            <?= Sessao::alert('ERRO'); ?>
            </section>
            <section class="container mx-auto text-center col-12 py-2">
                <div class="row mx-auto col-12">
                    <div class="card text-center m-3" style="width: 18rem;">
                        <div class="card-body">
                            <h5 class="card-title">CADASTRO</h5>
                            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                            <a href="#" class="btn btn-dark">ACESSAR</a>
                        </div>
                    </div>
                    <div class="card text-center m-3" style="width: 18rem;">
                        <div class="card-body">
                            <h5 class="card-title">CONFIGURACOES</h5>
                            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                            <a href="#" class="btn btn-dark">ACESSAR</a>
                        </div>
                    </div>
                    <div class="card text-center m-3" style="width: 18rem;">
                        <div class="card-body">
                            <h5 class="card-title">ESTOQUE</h5>
                            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                            <a href="#" class="btn btn-dark">ACESSAR</a>
                        </div>
                    </div>
                    <div class="card text-center m-3" style="width: 18rem;">
                        <div class="card-body">
                            <h5 class="card-title">FINANCEIRO</h5>
                            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                            <a href="#" class="btn btn-dark">ACESSAR</a>
                        </div>
                    </div>
                    <div class="card text-center m-3" style="width: 18rem;">
                        <div class="card-body">
                            <h5 class="card-title">VENDAS</h5>
                            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                            <a href="#" class="btn btn-dark">ACESSAR</a>
                        </div>
                    </div>
                    <div class="card text-center m-3" style="width: 18rem;">
                        <div class="card-body">
                            <h5 class="card-title">RECURSOS HUMANOS</h5>
                            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                            <a href="#" class="btn btn-dark">ACESSAR</a>
                        </div>
                    </div>
                </div>
            </section>
            <?php include_once 'inc/rodape.phtml';?>
        </div>
    </div>
</body>
</html>