<?php 
use Libraries\Sessao;
session_start();
include_once 'inc/cabecalho.phtml'; 
$qtdME = (is_array($modulos_empresa) ? count($modulos_empresa) : 0);
?>
<body class="" onload="atualizarDataHora();">
    <div class="d-flex" id="wrapper">
        <?php include_once 'inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
        <!-- Top navigation-->
        <?php include_once 'inc/menu_topo.phtml'; ?>
        <div class="container-fluid bg-light p-0">
            <header class="py-3">
                <section class="container px-5">
                    <div class="row gx-5 align-items-center justify-content-center">
                        <div class="col-lg-10 col-xl-10 col-xxl-10">
                            <div class="my-3 text-center text-xl-start">
                                <a class="text-decoration-none" href="<?= DIRPAGE; ?>admin/painel"><h3 class="display-5 text-center fw-bolder text-uppercase text-dark mb-2"><i class="bi bi-house"></i> Painel <span class="text-success">Administrativo</span></h3></a>
                            </div>
                        </div>
                        
                    </div>
                </section>
            </header>
            <section class="container py-2 text-center">
                <h4>BEM VINDO(A) <?= $usuario['USU_NOME'].' '.$usuario['USU_SOBRENOME'] ?></h4>
                <?= Sessao::alert('OK'); ?>
                <?= Sessao::alert('ERRO'); ?>
            </section>
            <hr>
            <section class="container mx-auto col-12 py-2">
                <?php if ($_SESSION['EMP_COD'] == 0) { ?>
                    <div class="row mx-auto m-4 ">
                        <div class="container col-8 ">
                            <div class="p-2 text-center text-white  bg-success rounded-3">
                                <h1 class="text-emphasis opacity-75">CADASTRE A SUA EMPRESA</h1>
                                <p class="lead fw-bold opacity-75">
                                Para utilizar o sitema LC<span class="text-dark">-TECH</span> é necessário que você cadastre o sua <b class="text-dark">empresa/negócio</b><p> crie e utilize ao máximo dos recursos disponíveis</p></p>
                
                                <a href="<?= DIRPAGE ?>cadastros/cadastro_empresas" class="col-auto btn btn-success text-uppercase">Clique aqui</a>
                            </div>
                        </div>
                        <div class="col-4 text-center text-lg-start opacity-50">
                            <h1 class="display-5 text-center fw-bolder text-uppercase text-3 mb-2">LC-<span class="text-success">TECH</span></h1>
                            <p class="col-lg lead text-center fs-6">DESENVOLVENDO SOLUÇÕES <br/>PARA O SEU NEGÓCIO</p>
                        </div>
                    </div>
                <?php }else { ?>
                    <div class="row col-10 mx-auto m-4 col-12">
                    <?php if ($qtdME != 0) { 
                        for ($i=0; $i < $qtdME; $i++) { ?>
                        <div class="card text-<?= $modulos_empresa[$i]['MOD_COR']; ?> m-1 py-3" style="max-width: 18rem;">
                            <a href="<?= DIRPAGE.$modulos_empresa[$i]['MOD_LINK']?>" class="col-auto link-light text-decoration-none">
                                <div class="card-header"><i class="bi bi-plus-square"></i> <?= $modulos_empresa[$i]['MOD_NOME']; ?></div>
                                <div class="card-body">
                                    <h5 class="card-title">Módulo de <?= $modulos_empresa[$i]['MOD_NOME']; ?></h5>
                                    <p class="card-text"><?= $modulos_empresa[$i]['MOD_DESCRICAO']; ?></p>
                                </div>
                            </a>
                        </div>
                        <?php } } ?>
                        
                        <div class="opacity-25 card text-bg-secondary mb-3" style="max-width: 18rem;">
                        <div class="card-header"><i class="bi bi-sliders"></i> CONFIGURAÇÕES</div>
                        <div class="card-body">
                            <h5 class="card-title">Módulo de configurações do sistema</h5>
                            <p class="card-text"></p>
                        </div>
                        </div>
                        <div class="opacity-25 card text-bg-danger mb-3" style="max-width: 18rem;">
                        <div class="card-header">FINANCEIRO</div>
                        <div class="card-body">
                            <h5 class="card-title">Módulo de Controle Financeiro</h5>
                            <p class="card-text"></p>
                        </div>
                        </div>
                        <div class="opacity-25 card text-bg-warning mb-3" style="max-width: 18rem;">
                        <div class="card-header">VENDAS</div>
                        <div class="card-body">
                            <h5 class="card-title">Módulo de Controle de Vendas</h5>
                            <p class="card-text"></p>
                        </div>
                        </div>
                        <div class="opacity-25 card text-bg-info mb-3" style="max-width: 18rem;">
                        <div class="card-header">RECURSOS HUMANOS</div>
                        <div class="card-body">
                            <h5 class="card-title">Módulo de Recursos Humanos</h5>
                            <p class="card-text"></p>
                        </div>
                        </div>

                        
                    </div>
                <?php } ?>
              
            </section>
            <?php include_once 'inc/rodape.phtml';?>
        </div>
    </div>
</body>
</html>