<?php 
use Libraries\Sessao;
session_start();
include_once 'app/Views/admin/inc/cabecalho.phtml'; 
$qtd = (is_array($empresas) ? count($empresas) : 0);
?>
<body class="">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
        <!-- Top navigation-->
        <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
        <div class="container-fluid bg-light p-0">
            <header class="py-3">
                <section class="container px-3">
                    <div class="row gx-3 align-items-center justify-content-center">
                        <div class="col-lg-9 col-xl-9 col-xxl-9">
                            <div class="my-1 px-4 mx-auto">
                                <a class="text-decoration-none" href="<?= DIRPAGE; ?>cadastros/empresas">
                                <h5 class="fs-2 fw-bolder text-uppercase text-dark mb-2"><i class="bi bi-plus-square"></i> Gerenciar <span class="text-success">Empresas/Negócios</span></h5></a>
                            </div>
                        </div>
                        <?php include_once 'app/Views/admin/inc/saudacao.phtml'; ?> 
                    </div>
                </section>
                <section class="container col-12 mx-auto px-5">
                        <?= $breadcrumb ?>
                </section>
            </header>
            <?php include_once 'app/Views/admin/inc/alertas.phtml'; ?>  
            <section class="bg-light py-2">
                <div class="container px-2 py-2 mx-auto row ">
                <?php if ($qtd == 0) { ?>
                            <div class="card bg-success text-center col-12 py-2 mb-4" style="width: 50rem;">
                                <div class="card-body  text-white">
                                    <h5 class="card-title">EMPRESAS/NEGÓCIOS</h5>
                                    <p class="card-text">Cadastre/Altere os dados dos seus usuários do sistema</p>
                                    <a href="<?= DIRPAGE ?>cadastros/cadastro_empresas" class="btn btn-dark">ACESSAR</a>
                                </div>
                            </div>
                        <?php }else { ?>
                            <div class="card bg-success text-center mx-auto mb-2" style="width: 50rem;">
                                <div class="card-body text-white">
                                    <h5 class="card-title">EMPRESAS/NEGÓCIOS</h5>
                                    <p class="card-text">Cadastre/Altere os dados dos seus usuários do sistema</p>
                                    <a href="<?= DIRPAGE ?>cadastros/cadastro_empresas" class="btn btn-dark">ACESSAR</a>
                                </div>
                            </div>
                            <table class="table table-striped table-bordered">
                                <thead class="text-center text-uppercase">
                                    <th class="text-dark">#</th>
                                    <th class="text-dark">Nome</th>
                                    <th class="text-dark">Regulamentacão</th>
                                    <th class="text-dark">Tipo</th>
                                    <th class="text-dark">Status</th>
                                    <th class="text-dark">Ações</th>
                                </thead>
                                <tbody>
                                <?php
                                    $b = 1;
                                    for ($i= 0; $i < $qtd; $i++) { ?>
                                    <tr class="">
                                        <td class="text-center align-middle"><?= $b; ?></td>
                                        <td class="text-center align-middle"><?= $empresas[$i]['EMP_NOME_FANTASIA']; ?></td>
                                        <td class="text-center align-middle"><?= $empresas[$i]['EMP_REGULAMENTACAO']; ?></td>
                                        <td class="text-center align-middle"><?= ($empresas[$i]['EMP_TIPO'] != '0')? (($empresas[$i]['EMP_TIPO'] == "PF")? 'PESSOA FÍSICA' : 'PESSOA JURÍDICA') : 'NÃO INFORMADO'; ?></td>
                                        <td class="text-center align-middle"><?= ($empresas[$i]['EMP_STATUS'] == 1)? 'ATIVO' : 'DESATIVADO'; ?></td>
                                        <td class="text-center align-middle">
                                            <a type="button" class="btn btn-warning btn-sm d-print-none" href="<?= DIRPAGE.'cadastros/alterar_empresas/'.$empresas[$i]['EMP_COD'].'/'.$_SESSION['USU_COD']; ?>" title="Alterar empresa"><i class="fa fa-edit"></i></a>
                                        </td>
                                    </tr>
                                <?php $b++; } ?>
                                </tbody>
                            </table>
                        <?php } ?>
                </div>
            </section>
            <?php include_once 'inc/rodape.phtml';?>
        </div>
    </div>
    
</body>
</html>