<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Libraries\\' => array($baseDir . '/libraries'),
    'Core\\' => array($baseDir . '/core'),
    'App\\Views\\' => array($baseDir . '/app/Views'),
    'App\\Models\\' => array($baseDir . '/app/Models'),
    'App\\Controllers\\' => array($baseDir . '/app/Controllers'),
    'App\\' => array($baseDir . '/app'),
);
