<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitf704e05ad16833fccd9ee3c4b67e1cac
{
    public static $prefixLengthsPsr4 = array (
        'L' => 
        array (
            'Libraries\\' => 10,
        ),
        'C' => 
        array (
            'Core\\' => 5,
        ),
        'A' => 
        array (
            'App\\Views\\' => 10,
            'App\\Models\\' => 11,
            'App\\Controllers\\' => 16,
            'App\\' => 4,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Libraries\\' => 
        array (
            0 => __DIR__ . '/../..' . '/libraries',
        ),
        'Core\\' => 
        array (
            0 => __DIR__ . '/../..' . '/core',
        ),
        'App\\Views\\' => 
        array (
            0 => __DIR__ . '/../..' . '/app/Views',
        ),
        'App\\Models\\' => 
        array (
            0 => __DIR__ . '/../..' . '/app/Models',
        ),
        'App\\Controllers\\' => 
        array (
            0 => __DIR__ . '/../..' . '/app/Controllers',
        ),
        'App\\' => 
        array (
            0 => __DIR__ . '/../..' . '/app',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitf704e05ad16833fccd9ee3c4b67e1cac::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitf704e05ad16833fccd9ee3c4b67e1cac::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitf704e05ad16833fccd9ee3c4b67e1cac::$classMap;

        }, null, ClassLoader::class);
    }
}
