<?php 
use Libraries\Sessao;
session_start();
include_once 'app/Views/admin/inc/cabecalho.phtml'; 
$qtd = (is_array($usuario) ? count($usuario) : 0);
?>
<body class="">
    <div class="d-flex" id="wrapper">
        <?php include_once 'app/Views/admin/inc/menu_lateral.phtml'; ?>
        <div id="page-content-wrapper">
        <!-- Top navigation-->
            <?php include_once 'app/Views/admin/inc/menu_topo.phtml'; ?>
            <div class="container-fluid bg-light p-0">
                <header class="py-3">
                    <section class="container px-3">
                        <div class="row gx-3 align-items-center justify-content-center">
                            <div class="col-lg-10 col-xl-10 col-xxl-10">
                                <div class="my-3 text-center text-xl-start">
                                    <a class="text-decoration-none" href="<?= DIRPAGE; ?>cadastros/alterar_usuarios">
                                        <h5 class="display-5 text-center fw-bolder text-uppercase text-dark mb-2">
                                            <i class="bi bi-person-circle"></i>Alterar <span class="text-success"> Usuário</span>
                                        </h5>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </section>
                </header>
                <section class="container py-2">
                <hr>
                <?= Sessao::alert('OK'); ?>
                <?= Sessao::alert('ERRO'); ?>
                </section>
                <section class="bg-light py-2">
                    <div class="container col-10 px-2 py-2 mx-auto row">
                        <form class="p-4 p-md-6 border text-uppercase rounded-3 bg-3" action="<?= DIRPAGE ?>cadastros/alterar_usuarios_empresa" method="POST">
                            <div class="row ">    
                                <div class="col-2 mb-2 form-floating ">
                                    <select class="form-select " name="USU_NIVEL">                                        
                                        <?php for ($i=1; $i <= 4; $i++) { ?>
                                            <option value="<?= $i?>" <?= (isset($_POST['USU_NIVEL']) &&  $_POST['USU_NIVEL']  == $i)? 'selected' : (($usuario['USU_NIVEL'] == $i)? 'selected'  : '') ?>><?= $i ?></option>
                                        <?php } ?>
                                    </select>
                                    <label class="form-label">NÍVEL DO USUÁRIO</label>
                                </div>
                                <div class="col-4 form-floating mb-3">
                                    <input type="text" class="form-control maiusculo" id="1" name="USU_NOME" placeholder="Informe seu nome" value="<?= isset($_POST['USU_NOME'])? $_POST['USU_NOME'] : (isset($usuario['USU_NOME']) ? $usuario['USU_NOME'] :''); ?>">
                                    <label class="px-3" for="1">Seu nome</label>
                                </div>    
                                <div class="col-6 form-floating mb-3">
                                    <input type="text" class="form-control maiusculo" id="2" name="USU_SOBRENOME" placeholder="Informe seu Sobrenome" value="<?= isset($_POST['USU_SOBRENOME'])? $_POST['USU_SOBRENOME'] : (isset($usuario['USU_SOBRENOME']) ? $usuario['USU_SOBRENOME'] : ''); ?>">
                                    <label class="px-3" for="2">Seu sobrenome</label>
                                </div> 
                            </div> 
                            <div class="row">
                                <hr>
                                <div class="col-5 text-center mb-3">
                                    <label for="inputPassword6" class="col-form-label">Seu Sexo</label>
                                    <div class="mx-auto text-center">   
                                        <div class="form-check form-check-inline">
                                            <input class="form-check-input" type="radio" name="USU_SEXO" id="flexRadioDefault2" value="1" <?= (isset($_POST['USU_SEXO']) && $_POST['USU_SEXO'] == 1) ? "checked" : ((isset($usuario['USU_SEXO']) && $usuario['USU_SEXO'] == 1)? "checked" : ''); ?>>
                                            <label class="form-check-label" for="flexRadioDefault2">
                                                Masculino
                                            </label>
                                        </div>
                                        <div class="form-check form-check-inline">
                                            <input class="form-check-input" type="radio" name="USU_SEXO" value="2" <?= (isset($_POST['USU_SEXO']) && $_POST['USU_SEXO'] == 2) ? "checked" : ((isset($usuario['USU_SEXO']) && $usuario['USU_SEXO'] == 2)? "checked" : ''); ?> id="flexRadioDefault1">
                                            <label class="form-check-label" for="flexRadioDefault1">
                                                Feminino
                                            </label>
                                        </div>
                                    </div>
                                </div> 
                                <div class="col-7 text-center mb-3">
                                    <label for="inputPassword6" class="col-form-label">Email de Acesso</label>
                                    <div class="form-floating mb-3">
                                        <input type="email" class="form-control" id="email" name="USU_EMAIL" placeholder="Informe seu email nome@examplo.com" value="<?= isset($_POST['USU_EMAIL']) ? $_POST['USU_EMAIL'] : (isset($usuario['USU_EMAIL']) ? $usuario['USU_EMAIL'] : ''); ?>">
                                        <label for="email">Seu Email</label>
                                    </div>
                                </div>
                                <hr class="my-4 text-dark">
                                <span class="text-center mb-3">A NOVA SENHA SERÁ: <b>123456</b> O USUÁRIO DEVERÁ ALTERÁ-LA</span>
                                <input type="hidden" class="form-control" name="USU_COD" value="<?= isset($_SESSION['USU_COD']) ? $_SESSION['USU_COD'] : 0; ?>">
                                <button class="w-100 btn btn-lg text-uppercase btn-success" name="CADASTRAR_NOVO_USUARIO" type="submit"><i class="fa fa-save"></i> Cadastrar</button>
                                <hr class="my-4 text-dark">
                            </div> 
                        </form>
                    </div>
                </section>
            <?php include_once 'app/Views/admin/inc/rodape.phtml';?>
        </div>
    </div>
</body>
</html>
                            