<?php 
use Libraries\Sessao;
session_start();
include_once 'app/Views/admin/inc/cabecalho.phtml'; 
?>
<body>
    <div class="bg-light ">
        <section class="container text-center">
            <?= Sessao::alert('OK'); ?>
            <?= Sessao::alert('ERRO'); ?>
         </section>
        <section class="mx-0">
            <table class="table table-success table-striped">
                <thead>
                    <tr class="fs-2 text-center">
                    <th colspan="5" scope="col-4">CAIXA <b class="text-danger">FECHADO</b></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>N° VENDA:</td>
                        <td colspan="2">DATA:</td>
                        <td colspan="2">OPERADOR:</td>
                       
                    </tr>
                    <tr>
                        <td>001</td>
                        <td colspan="2"><?= date('d/m/Y h:i:s') ?></td>
                        <td colspan="2"><?= isset($_SESSION['USU_NOME'])?$_SESSION['USU_NOME'] : 'FACA ACESSO!!' ?></td>
                    </tr>
                    <tr>
                        <td>CÓDIGO/PRODUTO:</td>
                        <td colspan="5">OPCÕES:</td>
                    </tr>
                        <tr> 
                            <td colspan="3">
                                <table>
                                    <tr  colspan="1">
                                    <td>
                                        <input type="text" class="form-control" name="PRO_COD" id="PRO_COD"/>
                                    </td></tr> <tr  colspan="1">
                                        <td><input type="text" class="form-control" name="PRO_COD" id="PRO_COD"  placeholder="DESC. %"  value=""></input>
                                    </td>
                                </tr></table>
                            </td>
                            <td colspan="2">
                                <textarea name="" class="form-control" id="" rows="10"></textarea>
                            </td>
                        <tr>
                            <tr >
                               
                                <tr >
                                <td >
                                    <input type="text" class="form-control" name="PRO_COD" id="PRO_COD" value="CONSUMIDOR"></input>
                                </td>
                                <td colspan="1">
                                    <td>
                                    <div class="card text-center mb-3" style="width: 18rem;">
                                        <div class="card-body">
                                            <h5 class="card-title">DESCONTO</h5>
                                            <p class="card-text">R$ 0,00</p>
                                        </div>
                                    </div>
                                    </td>
                                    <td>
                                    <div class="card text-center mb-3" style="width: 18rem;">
                                        <div class="card-body">
                                            <h5 class="card-title">TOTAL</h5>
                                            <p class="card-text">R$ 0,00</p>
                                        </div>
                                    </div>
                                    </td>
                                    <td>
                                    <div class="card text-center bg-success mb-3" style="width: 18rem;right:10%;">
                                        <div class="card-body">
                                            <h5 class="card-title">FINALIZAR</h5>
                                            
                                        </div>
                                    </div>
                                    </td>
                                </td>
                            </tr>
                            
                        </tr>
                    </tr>
                    
                </tbody>
            </table>
        </section>
        <?php include_once 'app/Views/admin/inc/rodape_pdv.phtml';?>
    </div>
</body>
</html>
           