<div class="border-end bg-dark" id="sidebar-wrapper">
    <div class="sidebar-heading bg-green-2 fundo2 fw-bold text-white">LC-TECH</div>
    <div class="list-group list-group-flush text-uppercase">
    <a class="list-group-item list-group-item-action list-group-item-dark p-4 px-3" title="Encerrar acesso ao sistema" href="<?= DIRPAGE?>login/sair"><i class="bi bi-box-arrow-right"></i> | Sair</a>
    </div>
</div>