<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <button class="btn btn-light" id="sidebarToggle"><span class="navbar-toggler-icon"></span></button>
        <button class="navbar-toggler text-white" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div id="navbarSupportedContent" class="collapse navbar-collapse">
            <ul class="navbar-nav ms-auto mt-2 mt-lg-0 fs-6 text-uppercase">
                <li>
                    <div class="container">   
                        <div class="col-md-12 fs-4 text-uppercase text-center text-3">
                            <span class="col-12" id="hora"></span>
                        </div>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Gerenciar</a>    
                    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="<?= DIRPAGE?>login/sair">Sair</a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>